### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhoudreames** [GDelevoye/cigarfilter#1]
following your installation, I got the error in this step:"conda build conda-recipe -c conda-forge"; 
this is my error:
![image](https://github.com/GDelevoye/cigarfilter/assets/54714639/dceade2f-18ca-4bb1-82e9-94bd85323589)
I don't know why, Is there any other way to install the software quickly？
In addition, I want to filter the CIGAR with N >10000 in RNA bam files, if there are no other methods to install this software, can you provide some simple code to achieve it？Thank~

this my bam file， of which the reads "9ae8a1cd-1a71-40d1-ab06-f1567ec79f9a" contained 1593N，I want to exclude it.
![image](https://github.com/GDelevoye/cigarfilter/assets/54714639/56a4f51f-7567-4ab9-acde-c023f98bff7a)

Dreames

**Comment by zhoudreames** [comment]
@GDelevoye I am so sorry to disturb you， can you  help me? Thanks~

**Comment by GDelevoye** [comment]
Hi @zhoudreames 

I've always been my own user for this software, but I am happy to see that it can be of any use for someone else. I'm checking your issue

**Comment by GDelevoye** [comment]
I think I will need some time to debug the conda package, but if you can't wait maybe you can use [this minimal example](https://github.com/GDelevoye/Example-.bam-filter-C-) ?

**Comment by GDelevoye** [comment]
Can you please try with [mamba]() like this and tell me if it works for you ? Sometimes it's just conda being completely stupid...

# Install mamba

```
wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
```

**Restart the terminal**

# Build and install the package with mamba instead of conda

```console
git clone https://github.com/GDelevoye/cigarfilter/
cd cigarfilter
mamba create -n cf cxx-compiler cmake make pip "conan<2" boa -c conda-forge
mamba actvate cf
conda mambabuild ./conda-recipe/ -c conda-forge
mamba install -c local cigarfilter
```

# Test that everything works

```console
(cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter -h
USAGE:
  cigarfilter [-?|-h|--help] [-f|--filter <filter name>] [-p|--print_header <bool>]

Display usage information.

OPTIONS, ARGUMENTS:
  -?, -h, --help          
  -f, --filter <filter name>
                          Use "cigarfilter_config help" for more info.
  -p, --print_header <bool>
                          When set to false, the header is not printed. <default: TRUE>

(cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter_config -h
  * help :
	 Displays this help

  * pluginpath :
	 Displays the path were filters are stored. Manually modify them only at your own risks.

  * list :
	 Lists all available filters.

  * add :
	 Adds a filter from a .cpp file (see README online at https://github.com/GDelevoye/cigarfilter).

  * remove :
	 Removes a filter. Example : "cigarfilter_config remove default".

  * clean :
	 Cleans all logs and temporary files.

  * purge :
	 Cleans all logs, temporary files and all filters except the default one.

(cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter_test
Running main() from /home/delevoye/.conan/data/gtest/1.12.1/_/_/build/bd0690086619c54f81a8365940843110bf637ce7/src/googletest/src/gtest_main.cc
[==========] Running 20 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 12 tests from cigar
[ RUN      ] cigar.t_listdigit
[       OK ] cigar.t_listdigit (0 ms)
[ RUN      ] cigar.t_eq
[       OK ] cigar.t_eq (0 ms)
[ RUN      ] cigar.t_empty
[       OK ] cigar.t_empty (0 ms)
[ RUN      ] cigar.t_S
[       OK ] cigar.t_S (0 ms)
[ RUN      ] cigar.t_D
[       OK ] cigar.t_D (0 ms)
[ RUN      ] cigar.t_I
[       OK ] cigar.t_I (0 ms)
[ RUN      ] cigar.t_X
[       OK ] cigar.t_X (0 ms)
[ RUN      ] cigar.t_N
[       OK ] cigar.t_N (0 ms)
[ RUN      ] cigar.t_P
[       OK ] cigar.t_P (0 ms)
[ RUN      ] cigar.t_H
[       OK ] cigar.t_H (0 ms)
[ RUN      ] cigar.t_M
[       OK ] cigar.t_M (0 ms)
[ RUN      ] cigar.complex_1
[       OK ] cigar.complex_1 (0 ms)
[----------] 12 tests from cigar (0 ms total)

[----------] 2 tests from plugin_helpers
[ RUN      ] plugin_helpers.plugindir
[       OK ] plugin_helpers.plugindir (16 ms)
[ RUN      ] plugin_helpers.get_default_plugin
[       OK ] plugin_helpers.get_default_plugin (17 ms)
[----------] 2 tests from plugin_helpers (33 ms total)

[----------] 6 tests from ExampleTest
[ RUN      ] ExampleTest.iterate_groups_t
[       OK ] ExampleTest.iterate_groups_t (51 ms)
[ RUN      ] ExampleTest.default_t
[       OK ] ExampleTest.default_t (51 ms)
[ RUN      ] ExampleTest.example1_t
[       OK ] ExampleTest.example1_t (50 ms)
[ RUN      ] ExampleTest.example2_t
[       OK ] ExampleTest.example2_t (50 ms)
[ RUN      ] ExampleTest.example3_t
[       OK ] ExampleTest.example3_t (51 ms)
[ RUN      ] ExampleTest.example4_t
ERROR : Could not remove the tmp file in fixture "StdoutFixture"
[       OK ] ExampleTest.example4_t (16 ms)
[----------] 6 tests from ExampleTest (272 ms total)

[----------] Global test environment tear-down
[==========] 20 tests from 3 test suites ran. (306 ms total)
[  PASSED  ] 20 tests.
```

**Comment by zhoudreames** [comment]
> **The previous minimal example should do exactly what you want**. However if you want, you can help me debugging what has gone wrong with the conda install. Sometimes it's just conda being completely stupid
> 
> This solution worked like a charm for me (and should in theory work in Ubuntu or MacOS), please let me know if you have any trouble with it :
> 
> # Install mamba
> ```
> wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
> bash Miniforge3-$(uname)-$(uname -m).sh
> ```
> 
> Once it is done, **Restart the terminal**
> 
> > If you don't do it, you'll have problems
> 
> # Build and install the package with mamba instead of conda
> Ensure that you are using mamba instead of conda, and then :
> 
> ```
> git clone https://github.com/GDelevoye/cigarfilter/
> cd cigarfilter
> mamba create -n cf cxx-compiler cmake make pip "conan<2" boa -c conda-forge
> mamba actvate cf
> conda mambabuild ./conda-recipe/ -c conda-forge
> mamba install -c local cigarfilter
> ```
> 
> # Test that everything works
> Make sure that you are using the "cf" mamba environment that was created in the previous script
> 
> ```
> (base) delevoye@Dell-G15-5530:~/cigarfilter$ mamba activate cf
> (cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter -h
> USAGE:
>   cigarfilter [-?|-h|--help] [-f|--filter <filter name>] [-p|--print_header <bool>]
> 
> Display usage information.
> 
> OPTIONS, ARGUMENTS:
>   -?, -h, --help          
>   -f, --filter <filter name>
>                           Use "cigarfilter_config help" for more info.
>   -p, --print_header <bool>
>                           When set to false, the header is not printed. <default: TRUE>
> 
> (cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter_config -h
>   * help :
> 	 Displays this help
> 
>   * pluginpath :
> 	 Displays the path were filters are stored. Manually modify them only at your own risks.
> 
>   * list :
> 	 Lists all available filters.
> 
>   * add :
> 	 Adds a filter from a .cpp file (see README online at https://github.com/GDelevoye/cigarfilter).
> 
>   * remove :
> 	 Removes a filter. Example : "cigarfilter_config remove default".
> 
>   * clean :
> 	 Cleans all logs and temporary files.
> 
>   * purge :
> 	 Cleans all logs, temporary files and all filters except the default one.
> 
> (cf) delevoye@Dell-G15-5530:~/cigarfilter$ cigarfilter_test
> Running main() from /home/delevoye/.conan/data/gtest/1.12.1/_/_/build/bd0690086619c54f81a8365940843110bf637ce7/src/googletest/src/gtest_main.cc
> [==========] Running 20 tests from 3 test suites.
> [----------] Global test environment set-up.
> [----------] 12 tests from cigar
> [ RUN      ] cigar.t_listdigit
> [       OK ] cigar.t_listdigit (0 ms)
> [ RUN      ] cigar.t_eq
> [       OK ] cigar.t_eq (0 ms)
> [ RUN      ] cigar.t_empty
> [       OK ] cigar.t_empty (0 ms)
> [ RUN      ] cigar.t_S
> [       OK ] cigar.t_S (0 ms)
> [ RUN      ] cigar.t_D
> [       OK ] cigar.t_D (0 ms)
> [ RUN      ] cigar.t_I
> [       OK ] cigar.t_I (0 ms)
> [ RUN      ] cigar.t_X
> [       OK ] cigar.t_X (0 ms)
> [ RUN      ] cigar.t_N
> [       OK ] cigar.t_N (0 ms)
> [ RUN      ] cigar.t_P
> [       OK ] cigar.t_P (0 ms)
> [ RUN      ] cigar.t_H
> [       OK ] cigar.t_H (0 ms)
> [ RUN      ] cigar.t_M
> [       OK ] cigar.t_M (0 ms)
> [ RUN      ] cigar.complex_1
> [       OK ] cigar.complex_1 (0 ms)
> [----------] 12 tests from cigar (0 ms total)
> 
> [----------] 2 tests from plugin_helpers
> [ RUN      ] plugin_helpers.plugindir
> [       OK ] plugin_helpers.plugindir (16 ms)
> [ RUN      ] plugin_helpers.get_default_plugin
> [       OK ] plugin_helpers.get_default_plugin (17 ms)
> [----------] 2 tests from plugin_helpers (33 ms total)
> 
> [----------] 6 tests from ExampleTest
> [ RUN      ] ExampleTest.iterate_groups_t
> [       OK ] ExampleTest.iterate_groups_t (51 ms)
> [ RUN      ] ExampleTest.default_t
> [       OK ] ExampleTest.default_t (51 ms)
> [ RUN      ] ExampleTest.example1_t
> [       OK ] ExampleTest.example1_t (50 ms)
> [ RUN      ] ExampleTest.example2_t
> [       OK ] ExampleTest.example2_t (50 ms)
> [ RUN      ] ExampleTest.example3_t
> [       OK ] ExampleTest.example3_t (51 ms)
> [ RUN      ] ExampleTest.example4_t
> ERROR : Could not remove the tmp file in fixture "StdoutFixture"
> [       OK ] ExampleTest.example4_t (16 ms)
> [----------] 6 tests from ExampleTest (272 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 20 tests from 3 test suites ran. (306 ms total)
> [  PASSED  ] 20 tests.
> ```

Thank you for the detailed replay, I try it.
